---
- name: Remove Access switch DHCP Guard configuration
  hosts: office_distro_switches

  tasks:

      - name: Disable IPv4 DHCP snooping
        ios_config:
          commands:
            - no ip dhcp snooping
            - no ip dhcp snooping vlan 1-4094
          match: exact
          save_when: always

      - name: Disable IPv6 DHCP guard and RAguard
        ios_config:
          parents: vlan configuration 1-4094
          commands:
            - no ipv6 dhcp guard
            - no ipv6 nd raguard
          match: exact
          save_when: always

      - name: Remove trust Interfaces for upstream DHCP servers
        ios_config:
          ios_config:
          parents: "interface {{ item }}"
          commands:
            - no ip dhcp snooping trust
          match: exact
          save_when: always
        loop: "{{ switch_trunks }}"
